services:
  api_gateway:
    build: ./http-api-gateway
    ports: 
      - '3000:3000'
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  users_microservice:
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    depends_on:
      - mysql
    command: sh -c "until mysql -h mysql -u testuser -p testuser123 -e 'SELECT 1'; do sleep 2; done; npx prisma migrate deploy && npm run start:dev"
  payments_microservice:
    build: ./payments-microservice
    volumes: 
      - ./payments-microservice/src:/usr/src/app/src
    command : npm run start:dev
  nats:
    image: nats
    ports:
      - 4222:4222
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nestjs_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307